### ISSUE TITLE
Allow Settings Guard changes to be reverted

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/Firefox-Shield#4]
This message is copied over from Issue #3

Currently when the Guard reports the changes in settings, the non-advanced user might have doubts - what to do.
If he doesn't change settings to default it might be dangerous.
If he changes settings to default it might also cause some unexpected behavior - especially with addon that caused changes in default setting.
So, it is highly desired to give the user (especially - non-advanced) ability to return to situation before he makes changes, i.e. to return to not default settings in case when default settings don't satisfy the user.
An advanced user can do it via about:config - he knows what to do, but for non-advanced user it is hard.
So, I propose the following.
1. To be able to call the Guard window dialog also by user initiative and not only when Guard finds something.
2. The window itself should list not only the changes to default settings that it recommends, but also the changes that were done by it earlier.
3. The user should be able:
a) to UNDO some changes that he did due to Guard recommendations
b) to DO some changes that Guard recommends, that were refused (cancelled) earlier

**Comment by jvillalobos** [comment]
> If he changes settings to default it might also cause some unexpected behavior - especially with addon that caused changes in default setting.

Generally, I don't expect changing these settings to break any add-ons. And users that install this extension are already looking for something that helps them reset their settings, so I don't think that they will second-guess themselves too much when faced with the option to reset the settings.

> 1. The window itself should list not only the changes to default settings that it recommends, but also the changes that were done by it earlier.
> 2. The user should be able:
>    a) to UNDO some changes that he did due to Guard recommendations
>    b) to DO some changes that Guard recommends, that were refused (cancelled) earlier

I don't know if this would be useful, specially for non-advanced users.  They won't know what keyword.URL or the user agent string are, but they will notice the faulty behavior caused by add-ons that change them. I don't see this sort of user setting it back to their previously modified values. As for the homepage, it is only reset in very specific circumstances, and it's not difficult to set it to whatever the user wants.

Worst case, they can reinstall the extension if they want the settings changes to happen again. However, we're generally aiming for users who got rid of the extension and are now stuck with settings changes they can't reset.

**Comment by difabor** [comment]
Let I explain the situation:
1. I installed this addon and he gave two warnings:
a) Default search
b) New page logo (something this).
2. Regarding a) I followed recomendation and changed the settings to default. Imediately I got warning from BrowserProtect 1.1.3. This BrowserProtect 1.1.3 might be wrong - I don't know.
3. Regarding b) - I use the Superstart as new page (the clicking on + button calls Superstart. I even don't know - does it relate to the worning b) or not, but if I change this setting to default and it suppress the Superstart I don't know how to return to it.The reinstalling Superstart will not return it (I had this problem) - I should delete this Addon with all its settings (that is very painful) and I'm not sure that even in this case it will solve this.
Moreover, in many cases I even don't know which addon caused changes and don't now what I should reinstall...
4. You should also understand, that the Guard's messages that can be very right and clear for advanced users might be totally unclear for amateurs like me - in this case following the Guard recommendation to set to default can also help such user to understand - about what is this message, but if the user has no simple way to rewert the settings, he will afraid to follow the recommendations. 
5. The things that are seen as simple for advanced user or developer might be very complicated, unclear etc. for amateurs - take this into account.

**Comment by jvillalobos** [comment]
> 1. Regarding a) I followed recomendation and changed the settings to default. Imediately I got warning from BrowserProtect 1.1.3. This BrowserProtect 1.1.3 might be wrong - I don't know.

It makes sense that you got a warning from Browser Protect, since it is designed to warn about those things. In fact, Settings Guard should be redundant since Browser Protect goes a few steps further in terms of features. The problem here is that you have 2 add-ons installed that do very similar things, so they step into each other's toes.

> 1. Regarding b) - I use the Superstart as new page (the clicking on + button calls Superstart. I even don't know - does it relate to the worning b) or not, but if I change this setting to default and it suppress the Superstart I don't know how to return to it.The reinstalling Superstart will not return it (I had this problem) - I should delete this Addon with all its settings (that is very painful) and I'm not sure that even in this case it will solve this.

Generally, installing the add-on again should change the settings again. I don't know the details about Superstart, though. You should, however, understand that the add-on is meant to reset your settings. You get the option to not reset them, but you are installing it for that specific purpose. I think that making it possible to undo these changes would just make everything more difficult to understand.

> 1. You should also understand, that the Guard's messages that can be very right and clear for advanced users might be totally unclear for amateurs like me

Absolutely. That's the reason it's not fully reviewed on AMO and it's not being very heavily promoted. We need to work on the messages and user experience so that everything is as clear as possible. For now it's just an initial version.

Thank you for all the feedback. I'll keep this issue open to give it more thought.
